In [2]:
import pandas as pd

In [16]:
df = pd.read_csv('data/Fish.csv')
df.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [19]:
cond = df['Species'].isin(['Bream','Smelt']) #b와 s가 아닌 부분은 false

In [20]:
df.loc[cond] #cond에 맞는 애들을 슬라이싱

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
5     Bream   450.0     26.8     29.7     34.7  13.6024  4.9274
6     Bream   500.0     26.8     29.7     34.5  14.1795  5.2785
7     Bream   390.0     27.6     30.0     35.0  12.6700  4.6900
8     Bream   450.0     27.6     30.0     35.1  14.0049  4.8438
9     Bream   500.0     28.5     30.7     36.2  14.2266  4.9594
10    Bream   475.0     28.4     31.0     36.2  14.2628  5.1042
11    Bream   500.0     28.7     31.0     36.2  14.3714  4.8146
12    Bream   500.0     29.1     31.5     36.4  13.7592  4.3680
13    Bream   340.0     29.5     32.0     37.3  13.9129  5.0728
14    Bream   600.0     29.4     32.0     37.2  14.9544  5.1708
15    Bream   600.0     29.4     32.0     37.2  15.4380  5.5800
16    Bream   700.0     30.4     33.0     38.3  14.8604  5.2854
17    Bream   700.0     30.4     33.0     38.5  14.9380  5.1975
18    Bream   610.0     30.9     33.5     38.6  15.6330  5.1338
19    Bream   650.0     31.0     33.5     38.7  14.4738  5.7276
20    Bream   575.0     31.3     34.0     39.5  15.1285  5.5695
21    Bream   685.0     31.4     34.0     39.2  15.9936  5.3704
22    Bream   620.0     31.5     34.5     39.7  15.5227  5.2801
23    Bream   680.0     31.8     35.0     40.6  15.4686  6.1306
24    Bream   700.0     31.9     35.0     40.5  16.2405  5.5890
25    Bream   725.0     31.8     35.0     40.9  16.3600  6.0532
26    Bream   720.0     32.0     35.0     40.6  16.3618  6.0900
27    Bream   714.0     32.7     36.0     41.5  16.5170  5.8515
28    Bream   850.0     32.8     36.0     41.6  16.8896  6.1984
29    Bream  1000.0     33.5     37.0     42.6  18.9570  6.6030
30    Bream   920.0     35.0     38.5     44.1  18.0369  6.3063
31    Bream   955.0     35.0     38.5     44.0  18.0840  6.2920
32    Bream   925.0     36.2     39.5     45.3  18.7542  6.7497
33    Bream   975.0     37.4     41.0     45.9  18.6354  6.7473
34    Bream   950.0     38.0     41.0     46.5  17.6235  6.3705
145   Smelt     6.7      9.3      9.8     10.8   1.7388  1.0476
146   Smelt     7.5     10.0     10.5     11.6   1.9720  1.1600
147   Smelt     7.0     10.1     10.6     11.6   1.7284  1.1484
148   Smelt     9.7     10.4     11.0     12.0   2.1960  1.3800
149   Smelt     9.8     10.7     11.2     12.4   2.0832  1.2772
150   Smelt     8.7     10.8     11.3     12.6   1.9782  1.2852
151   Smelt    10.0     11.3     11.8     13.1   2.2139  1.2838
152   Smelt     9.9     11.3     11.8     13.1   2.2139  1.1659
153   Smelt     9.8     11.4     12.0     13.2   2.2044  1.1484
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

In [21]:
lw_df = df.loc[cond, ['Length2', 'Weight']] #필요한 칼럼만 뽑아내기

In [28]:
#lw_df에 들어있는 값만 알고 싶습니다 
#2차원으로 바꾸고 싶은 상황 
fish_data = lw_df.values.tolist()

In [29]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier

In [30]:
fish_target = [1]*35 + [0]*14

In [35]:
train_input = fish_data[:35]
train_target = fish_target[:35]

test_input = fish_data[:35]
test_target = fish_target[:35]

In [36]:
kn.fit(train_input, train_target)
kn.score(test_input, test_target)

AttributeError: 'list' object has no attribute '_validate_params'

In [39]:
import numpy as np

In [43]:
fish_arr = np.array(fish_data)
target_arr = np.array(fish_target)
#넘파이 활용해서 강제로 array로 바꿈 #fancy 인덱싱 가능

In [45]:
np.random.seed(42)
index = np.arange(49) #0~49 만들어서 
np.random.shuffle(index) #랜덤으로 말해줘 
print(index)

[13 45 47 44 17 27 26 25 31 19 12  4 34  8  3  6 40 41 46 15  9 16 24 33
 30  0 43 32  5 29 11 36  1 21  2 37 35 23 39 10 22 18 48 20  7 42 14 28
 38]

In [53]:
test_input = fish_arr[index[:35]]
train_target = target_arr[index[:35]]

test_input = fish_arr[index[:35]]
test_target = target_arr[index[:35]]

In [56]:
import matplotlib.pyplot as plt

plt.scatter(train_input[;, 0], train_input[;, 1])
plt.show()

SyntaxError: invalid syntax (4276153115.py, line 3)